# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 8, 11, 15 ] # LTS and actual versions

    name: Java ${{ matrix.java }} build

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Compile java ${{ matrix.java }}
        run: mvn clean compile -P-nodejs-all -P-showcase-with-thorntails-in-docker

      - name: Test java ${{ matrix.java }}
        run: mvn test -P-nodejs-all -P-showcase-with-thorntails-in-docker

      - name: Build java ${{ matrix.java }}
        run: mvn package -P-nodejs-all -P-showcase-with-thorntails-in-docker

      - name: Build java and node ${{ matrix.java }}
        run: mvn package -P nodejs-all -P-showcase-with-thorntails-in-docker
